### PR TITLE
VNC Viewer icon

### PR DESCRIPTION
**Pull request by adueppen**
Icons remain available [here](https://copy.com/O3uEks8ZUFLbMsod) under the obvious names. (Yes all my pull requests are going to say this, deal with it)

### CODE REVIEW

**Comment by loctauxphilippe** [comment]
@adueppen why do you put the icons on copy? just use github! they render nicely, without to have to go on another website

**Comment by adueppen** [comment]
It's because Corbin needs to check the SVGs and save them as AI files, so it works out fine to have them in copy since it uploads them automatically.

**Comment by loctauxphilippe** [comment]
@adueppen oh ok, I didn't know :)

**Comment by crutchcorn** [comment]
May the record state that this may be my favorite Pinbadge icon yet.

Anyways - I won't be home most of the day. I'll merge when I can

**Comment by crutchcorn** [comment]
Took a look at the SVG and everything was PERFECT! Keep it up like this and I'll just add you to the repo and we can switch from saving as AI to SVG! :D

**Comment by adueppen** [comment]
Just know that I'll probably still have to send my SVGs to you until I figure out a good strategy to push to the other branch. I really wish Github would make a Linux GUI :cry:.

**Comment by crutchcorn** [comment]
Use SmartGit. AMAZING GUI for Linux as well

**Pull request merged**
