### PR TITLE
File Roller icon

### PR DESCRIPTION
**Pull request by adueppen**
Icons remain available [here](https://copy.com/O3uEks8ZUFLbMsod) under the obvious names.

### CODE REVIEW

**Comment by adueppen** [comment]
I also added in the README that Numix is recommended for the missing icons at the moment.

**Comment by loctauxphilippe** [comment]
@adueppen why do you have a copy of your icons on copy?

**Comment by loctauxphilippe** [comment]
for the icon, you need to deal with Corbin, but can you revert your commit for the readme?

**Comment by adueppen** [comment]
The copy of the SVGs are online since Corbin needs them for the ai branch. How do I revert a commit? I've never been that good with anything besides simple operations in Git.

**Comment by adueppen** [comment]
Also, why do I need to revert the commit to the README?

**Comment by crutchcorn** [comment]
Yeah, I'm not entirely sure why he should revert the commit. However, I am going to merge this and modify the README.md AFTER doing so

**Pull request merged**
