### PR TITLE
Icon for Wine

### PR DESCRIPTION
**Pull request by adueppen**

### CODE REVIEW

**Comment by adueppen** [comment]
Raster preview because Github doesn't really support viewing SVGs that well

**Comment by crutchcorn** [comment]
Visually, it LOOKS good. Let me open up the SVG and check how you made things.

**Comment by adueppen** [comment]
If I should group the parts of the glyph, I can do that.

**Comment by crutchcorn** [comment]
A few things to note:
* For 48x48px canvas icons, the glyph MUST be 25px max, not 24.979 px max. (the glyph was found to be 24.979x24.979 px)
* Glyph objects must be grouped together in a group called `Glyph`
* Tints must be grouped together in a group called `Glyph Tint`
* Shades must be grouped together in a group called `Glyph Shade`
* `Glyph Shade` MUST be below `Glyph`
* `Glyph Tint` MUST be above `Glyph`
If you would like, I can be able to send you an SVG of what this icon would look like completely edited so that you can study and correct your pull request.

**Comment by crutchcorn** [comment]
Another note about the Shade. We don't use black. Please refer to the Material Design iconography guide to decide which color should be used for the shade. If you are confused about this, message me on hangouts and I will help you

**Pull request closed without merging**
